package org.vitaly.connectionPool.abstraction;

import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Created by vitaly on 2017-03-25.
 */
public interface PooledConnection extends AutoCloseable {
    void initializeTransaction();

    PreparedStatement prepareStatement(String sql) throws SQLException;

    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;

    void commit();

    void rollback();

    @Override
    void close();
}
