package org.vitaly.connectionPool.implementation;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.vitaly.connectionPool.abstraction.PooledConnection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * Created by vitaly on 2017-03-25.
 */
public class MysqlPooledConnection implements PooledConnection {
    private static final Logger logger = LogManager.getLogger();

    private Connection connection;
    private boolean isTransactionInitialized;
    private boolean isTransactionEnded;

    MysqlPooledConnection(Connection connection) {
        this.connection = connection;
        this.isTransactionInitialized = false;
        this.isTransactionEnded = false;
    }

    @Override
    public void initializeTransaction() {
        try {
            connection.setAutoCommit(false);
            isTransactionInitialized = true;
            isTransactionEnded = false;
        } catch (SQLException e) {
            logger.error("Error while initializing transaction.", e);
            throw new IllegalStateException(e);
        }
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public void commit() {
        try {
            connection.commit();
            isTransactionEnded = true;
            connection.setAutoCommit(true);
        } catch (SQLException e) {
            logger.error("Error while committing transaction.", e);
            throw new IllegalArgumentException(e);
        }
    }

    @Override
    public void rollback() {
        try {
            connection.rollback();
            isTransactionEnded = true;
            connection.setAutoCommit(true);
        } catch (SQLException e) {
            logger.error("Error while rolling back transaction.", e);
            throw new IllegalArgumentException(e);
        }
    }

    @Override
    public void close() {
        try {
            if (isTransactionInitialized && !isTransactionEnded) {
                rollback();
            }
            connection.close();
        } catch (SQLException e) {
            logger.error("Error while closing connection.", e);
            throw new IllegalStateException(e);
        }
    }
}
